### ISSUE TITLE
Attempt to get length of null array

### ISSUE THREAD

**Issue by SferaDev** [SferaDev/DanaCast#14]
**Number:** 	 16 

**URL:** 	 https://instabug.com/applications/danacast/issues/16 

**Type:** 	 crash 

**Status:** 	 New 

**Email:** 	 [tomgus1.2@gmail.com, tim-j-g@hotmail.co.uk, tim-j-g@hotmail.co.uk] 

**Comment:**
```
java.lang.NullPointerException: Attempt to get length of null array
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:142)
	at java.util.Arrays.sort(Arrays.java:1957)
	at com.sferadev.danacast.utils.ContentUtils.listFiles(ContentUtils.java:212)
	at com.sferadev.danacast.activities.MainActivity.onItemClick(MainActivity.java:265)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3057)
	at android.widget.AbsListView$3.run(AbsListView.java:3864)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5290)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)


``` 

**Location:** 	 N/A 

**Device:** 	 OnePlus ONE A2003 / SDK Level 22 

**Memory:** 	 Used: 1807 MB, Free: 1901 MB 

**Storage:** 	 Used: 7849 MB, Free: 47384 MB 

**Connectivity:** 	 Carrier: O2-UK, WiFi: BTHub4-RFHW 

**Battery:** 	 56 , Unplugged 

**App Version:** 	 1.2.2 (122) 

**Duration:** 	 00:00:00 

**User Data:** 	  

**Console Log:**
```
--------- beginning of main
09-24 21:46:31.896 I/MediaRouter(22284): Found default route: MediaRouter.RouteInfo uniqueId=android/.support.v7.media.SystemMediaRouteProvider:DEFAULT_ROUTE, name=Phone, description=null, enabled=true, connecting=false, canDisconnect=false, playbackType=0, playbackStream=3, volumeHandling=1, volume=1, volumeMax=15, presentationDisplayId=-1, extras=null, settingsIntent=null, providerPackageName=android 
09-24 21:46:31.962 I/AppCompatViewInflater(22284): app:theme is now deprecated. Please move to using android:theme instead.
09-24 21:46:32.498 D/AppTracker(22284): App Event: start
09-24 21:46:32.520 D/OpenGLRenderer(22284): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
09-24 21:46:32.557 I/Adreno  (22284): QUALCOMM build                   : ef88d8e, I555dfb505a
09-24 21:46:32.557 I/Adreno  (22284): Build Date                       : 06/08/15
09-24 21:46:32.557 I/Adreno  (22284): OpenGL ES Shader Compiler Version: E031.25.03.09
09-24 21:46:32.557 I/Adreno  (22284): Local Branch                     : 
09-24 21:46:32.557 I/Adreno  (22284): Remote Branch                    : quic/LA.BF64.1.2.1.c1_rb1.5
09-24 21:46:32.557 I/Adreno  (22284): Remote Branch                    : NONE
09-24 21:46:32.557 I/Adreno  (22284): Reconstruct Branch               : NOTHING
09-24 21:46:32.570 I/OpenGLRenderer(22284): Initialized EGL, version 1.4
09-24 21:46:32.586 D/OpenGLRenderer(22284): Enabling debug mode 0
09-24 21:46:32.601 D/AbstractTracker(22284): Event success
09-24 21:46:32.691 I/Timeline(22284): Timeline: Activity_idle id: android.os.BinderProxy@1487eed3 time:6068467
09-24 21:46:37.941 D/AndroidRuntime(22284): Shutting down VM

``` 

**Instabug Log:**
```

``` 

**User Steps:**
```
09-24 21:09:32     com.sferadev.danacast.activities.MainActivity was resumed 
09-24 21:09:35     In activity com.sferadev.danacast.activities.MainActivity: View(drawer_text) of type android.support.v7.widget.AppCompatTextView received a click event
09-24 21:09:35     In activity com.sferadev.danacast.activities.MainActivity: View(drawer_text) of type android.support.v7.widget.AppCompatTextView received a click event
09-24 21:09:37     In activity com.sferadev.danacast.activities.MainActivity: View(drawer_text) of type android.support.v7.widget.AppCompatTextView received a click event
09-24 21:09:37     In activity com.sferadev.danacast.activities.MainActivity: View(drawer_text) of type android.support.v7.widget.AppCompatTextView received a click event
```

**Comment by SferaDev** [comment]
Fixed
