### ISSUE TITLE
Unable to start activity ComponentInfocom.sferadev.danacast/com.sferadev.danacast.activities.MainActivity: java.lang.NullPointerException

### ISSUE THREAD

**Issue by SferaDev** [SferaDev/DanaCast#16]
**Number:** 	 18 

**URL:** 	 https://instabug.com/applications/danacast/issues/18 

**Type:** 	 crash 

**Status:** 	 New 

**Email:** 	  

**Comment:**
```
java.lang.RuntimeException: Unable to start activity ComponentInfocom.sferadev.danacast/com.sferadev.danacast.activities.MainActivity: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2411)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5323)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.sferadev.danacast.activities.MainActivity.updateListview(MainActivity.java:281)
	at com.sferadev.danacast.activities.MainActivity.handleIntent(MainActivity.java:290)
	at com.sferadev.danacast.activities.MainActivity.onCreate(MainActivity.java:100)
	at android.app.Activity.performCreate(Activity.java:5343)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2323)
	... 11 more

Caused by: 
java.lang.NullPointerException
	at com.sferadev.danacast.activities.MainActivity.updateListview(MainActivity.java:281)
	at com.sferadev.danacast.activities.MainActivity.handleIntent(MainActivity.java:290)
	at com.sferadev.danacast.activities.MainActivity.onCreate(MainActivity.java:100)
	at android.app.Activity.performCreate(Activity.java:5343)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2323)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2411)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5323)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)


``` 

**Location:** 	 N/A 

**Device:** 	 bq Edison 3 / SDK Level 19 

**Memory:** 	 Used: 1268 MB, Free: 718 MB 

**Storage:** 	 Used: 4507 MB, Free: 23026 MB 

**Connectivity:** 	 Carrier: , WiFi: CFRR2 

**Battery:** 	 62 , Unplugged 

**App Version:** 	 1.2.0 (120) 

**Duration:** 	 00:00:00 

**User Data:** 	  

**Console Log:**
```
20.644 W/System.err(31033): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-21 12:06:20.644 W/System.err(31033): 	at java.lang.reflect.Method.invoke(Method.java:515)
09-21 12:06:20.644 W/System.err(31033): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
09-21 12:06:20.644 W/System.err(31033): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
09-21 12:06:20.644 W/System.err(31033): 	at dalvik.system.NativeStart.main(Native Method)
09-21 12:06:20.644 W/System.err(31033): Caused by: java.lang.NullPointerException
09-21 12:06:20.645 W/System.err(31033): 	at com.sferadev.danacast.activities.MainActivity.updateListview(MainActivity.java:281)
09-21 12:06:20.645 W/System.err(31033): 	at com.sferadev.danacast.activities.MainActivity.handleIntent(MainActivity.java:290)
09-21 12:06:20.645 W/System.err(31033): 	at com.sferadev.danacast.activities.MainActivity.onCreate(MainActivity.java:100)
09-21 12:06:20.645 W/System.err(31033): 	at android.app.Activity.performCreate(Activity.java:5343)
09-21 12:06:20.645 W/System.err(31033): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
09-21 12:06:20.645 W/System.err(31033): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2323)
09-21 12:06:20.645 W/System.err(31033): 	... 11 more
09-21 12:06:20.645 W/dalvikvm(31033): threadid=1: calling UncaughtExceptionHandler
09-21 12:06:20.652 D/MediatekClassFactory(31033): createInstance(): Begin = 325974649
09-21 12:06:20.652 D/MediatekClassFactory(31033): create Instance with :  interface com.mediatek.common.telephony.IOnlyOwnerSimSupport
09-21 12:06:20.652 W/MediatekClassFactory(31033): Tablet not exist!, Get obj from default class
09-21 12:06:20.652 D/MediatekClassFactory(31033): create Instance from tablet library :  com.mediatek.tb.telephony.OnlyOwnerSimSupport
09-21 12:06:20.652 D/MediatekClassFactory(31033): createInstance(): End = 325974650
09-21 12:06:20.658 D/WifiManager(31033): Enter init, sThreadRefCount:0
09-21 12:06:20.660 E/WifiManager(31033): mWifiServiceMessenger == null
09-21 12:06:20.670 D/dalvikvm(31033): create interp thread : stack size=128KB
09-21 12:06:20.670 D/dalvikvm(31033): create new thread
09-21 12:06:20.670 D/dalvikvm(31033): new thread created
09-21 12:06:20.670 D/dalvikvm(31033): update thread list
09-21 12:06:20.670 D/dalvikvm(31033): threadid=12: interp stack at 0x60542000
09-21 12:06:20.670 D/dalvikvm(31033): init ref table
09-21 12:06:20.670 D/dalvikvm(31033): init mutex
09-21 12:06:20.670 D/dalvikvm(31033): threadid=12: created from interp
09-21 12:06:20.670 D/dalvikvm(31033): start new thread
09-21 12:06:20.670 D/dalvikvm(31033): threadid=12: notify debugger
09-21 12:06:20.670 D/dalvikvm(31033): threadid=12 (java.lang.ProcessManager): calling run()
09-21 12:06:20.677 D/dalvikvm(31033): threadid=14: interp stack at 0x60564000
09-21 12:06:20.677 D/dalvikvm(31033): init ref table
09-21 12:06:20.677 D/dalvikvm(31033): init mutex

``` 

**Instabug Log:**
```

``` 

**User Steps:**
```

```

**Comment by SferaDev** [comment]
Old version, cannot replicate
